# Generated by Django 5.2.2 on 2025-06-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rating', models.FloatField()),
                ('reviews_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
